'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace My

    Partial Friend Class MyApplication
        Inherits Global.Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase

        <Global.System.Diagnostics.DebuggerStepThrough()>
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = False
            Me.EnableVisualStyles = True
            Me.SaveMySettingsOnExit = True
            Me.ShutdownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub

        <Global.System.Diagnostics.DebuggerStepThrough()>
        Protected Overrides Sub OnCreateMainForm()
            ' ⚠️ Cambiá "Form1" por el nombre real de tu formulario principal
            Me.MainForm = Global.NuevaApp.Form1
        End Sub

    End Class
End Namespace

